### ISSUE TITLE
Kustomize `op` Patches cause a Panic

### ISSUE THREAD

**Issue by seanturner026** [dag-andersen/argocd-diff-preview#35]
The `kustomize` `op` patches appear to cause a panic _I believe_ because the patch "manifest" is consumed by the rust code, and, doesn't have a `metadata` top-level field. If I had to guess here (not a rust developer): https://github.com/dag-andersen/argocd-diff-preview/blob/4018a125bd1e4ffc7bbcb66953d6a712ee7f3a7c/src/parsing.rs#L130-L133

I suspect some logic could be added that understands that this is a patch file if the manifest is a yaml array?

Reproduction is here: https://github.com/seanturner026/argocd-applicationset/pull/16

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_yaml-0.9.34+deprecated/src/value/index.rs:107:18:
cannot access key "metadata" in YAML sequence
stack backtrace:
   0:     0x55b689a195a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
   1:     0x55b689a4232b - core::fmt::write::hc090a2ffd6b28c4a
   2:     0x55b689a1606f - std::io::Write::write_fmt::h8898bac6ff039a23
   3:     0x55b689a1937e - std::sys_common::backtrace::print::ha96650907276675e
   4:     0x55b689a1a639 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
   5:     0x55b689a1a37d - std::panicking::default_hook::h207342be97478370
   6:     0x55b689a1aad3 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
   7:     0x55b689a1a9b4 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
   8:     0x55b689a19a69 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
   9:     0x55b689a1a6e7 - rust_begin_unwind
  10:     0x55b689833503 - core::panicking::panic_fmt::hdc63834ffaaefae5
  11:     0x55b6898c72db - <str as serde_yaml::value::index::Index>::index_or_insert::hd6d0c1c95c13231b
  12:     0x55b68987c5a0 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::hff88f73c16dfea7b
  13:     0x55b689884c30 - alloc::vec::in_place_collect::from_iter_in_place::hdc2e306cc50df39d
  14:     0x55b68983b4bf - argocd_diff_preview::parsing::get_applications::{{closure}}::h5663ff95e448d371
  15:     0x55b6898430a7 - argocd_diff_preview::main::{{closure}}::hd46a67bf7e27a527
  16:     0x55b689837695 - tokio::runtime::park::CachedParkThread::block_on::heeaa189f831dfbc9
  17:     0x55b6898720ad - tokio::runtime::runtime::Runtime::block_on::h110d3d393288d378
  18:     0x55b68986d1bc - argocd_diff_preview::main::h27bd70ec1900b1c5
  19:     0x55b689885ef3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d4959767a14ecdc
  20:     0x55b68987f489 - std::rt::lang_start::{{closure}}::h6dce2a7c30d504f8
  21:     0x55b689a0f6e0 - std::rt::lang_start_internal::h3ed4fe7b2f419135
  22:     0x55b68986d295 - main
  23:     0x7f25addbd24a - <unknown>
  24:     0x7f25addbd305 - __libc_start_main
  25:     0x55b689833c1a - _start
  26:                0x0 - <unknown>
```

**Comment by dag-andersen** [comment]
Hi @seanturner026 
Thank you for reporting this issue! 🚀 

I have fixed it in version `v0.0.13` ([PR](https://github.com/dag-andersen/argocd-diff-preview/pull/37))
`argocd-diff-preview` It will now check if `kind` equals `Application` or `ApplicationSet`, before doing any patching.

Running this seems to work ⬇️  :) 
```
git clone https://github.com/seanturner026/argocd-applicationset base-branch --depth 1 -q
git clone https://github.com/seanturner026/argocd-applicationset target-branch --depth 1 -q -b issue-example
docker run \
   --network host \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v $(pwd)/output:/output \
   -v $(pwd)/base-branch:/base-branch \
   -v $(pwd)/target-branch:/target-branch \
   -e TARGET_BRANCH=issue-example \
   -e REPO=seanturner026/argocd-applicationset \
   -e KUSTOMIZE_BUILD_OPTIONS="--load-restrictor LoadRestrictionsNone --enable-helm" \
   dagandersen/argocd-diff-preview:v0.0.13
```

**Comment by seanturner026** [comment]
Cheers! Definitely no more panic.

Are these patches examples of something that needs to be generated per the README.md?

```
    - name: Generate with kustomize
      run: kustomize build pull-request/some/path/my-kustomize > pull-request/rendered-apps.yaml
```

**Comment by dag-andersen** [comment]
I’m not sure I understand the question! :)

However, the example seems to describe a scenario where some teams do not store any raw application YAML files in their repository. Instead, they use tools like Helm or Kustomize to generate all their applications. In these cases, they must manually generate or build the applications before running the tool.

I can see that you also generate your application with Kustomize: [clusters/staging/kustomization.yaml](https://github.com/seanturner026/argocd-applicationset/blob/main/clusters/staging/kustomization.yaml)

However, since your Kustomize template does not modify the ApplicationSet, you don’t need to manually build Kustomize.  The tool should find [clusters/staging/argocd-appset.yaml](https://github.com/seanturner026/argocd-applicationset/blob/main/clusters/staging/argocd-appset.yaml) without any problems :)

**Comment by seanturner026** [comment]
Yeah, I can see where the confusion came from 😅 

Basically, after this change, that kustomization patch wasn't being picked up by the github action:

https://github.com/seanturner026/argocd-applicationset/pull/22
https://github.com/seanturner026/argocd-applicationset/pull/23

I thought there was maybe a regression where patching was broken in v0.13.0, but, that doesn't seem to be the case:

https://github.com/seanturner026/argocd-applicationset/pull/24

I guess 22 and 23 aren't being picked up because they're patching CRDs? A regular `kustomize build` command definitely picks them up.

Either way, shall close this for now. Thanks again!

**Comment by dag-andersen** [comment]
@seanturner026 

No problem! 😄 

I believe your `karpenter-crds` changes are not picked up because those files are not rendered by any of your argocd apps? That karpenter-folder does not seem to be captured by your [argocd-appset.yaml](https://github.com/seanturner026/argocd-applicationset/blob/main/clusters/staging/argocd-appset.yaml#L26)

Anyway, feel free to open a new issue if you suspect you’ve found a problem! 🚀
