### ISSUE TITLE
Support private repos

### ISSUE THREAD

**Issue by sorrison** [dag-andersen/argocd-diff-preview#63]
Just been to your argocon talk and this tool is just what I've been missing.

Most of our apps are helm charts stored in a private oci registry so I need a way of adding some creds to the argo install https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/

This doesn't look possible so would be a great addition.

**Comment by dag-andersen** [comment]
Hi @sorrison! :)
Thank you for your interest in the project. This should already be supported as long as you give the tool an ArgoCD secret for accessing the private OCI registry.

You should be able to create a secret similar to how it is shown in [this example](https://dag-andersen.github.io/argocd-diff-preview/github-actions-workflow/) and mount it under `/secrets`. Since there are numerous ways to create secrets for ArgoCD, you will need to figure out how the secret should be formatted. If you have kubectl access to your live cluster, I suggest just running `kubectl get secrets -n argocd` and checking how your live ArgoCD instance currently authenticates with the OCI registry and try to replicate that for the local ArgoCD instance.

I hope this helps. If not, please let me know, and we'll dig deeper into the problem. I may be missing something 🚀

**Comment by sorrison** [comment]
Ahh perfect, I somehow missed that in the docs. Thanks!
