### ISSUE TITLE
Resource cleanup (kind/minikube) on failure

### ISSUE THREAD

**Issue by davidfrickert** [dag-andersen/argocd-diff-preview#68]
Would it be possible to attempt a graceful cleanup of the kind / minikube cluster when a failure or termination occurs?

At the moment, if the app panics, or is terminated (e.g. by terminating a CI pipeline) somewhere after creating the cluster, it will not be removed and will stay there for eternity which is not ideal.

I'm not familiar with rust so unsure how that would be implemented, but some hook that could trigger the cluster deletion if a panic or SIGTERM is detected would be nice. In the Java world this would be a Shutdown Hook, I hope there is something similar in rust.

Perhaps https://doc.rust-lang.org/std/panic/fn.catch_unwind.html could work? Or maybe refactor the code such that panic's don't occur and errors are handled gracefully!

**Comment by dag-andersen** [comment]
Hi @davidfrickert 

Great point!

I hadn’t really thought of it as an issue since GitHub-hosted runners automatically clean everything up when the workflow finishes. Keeping the cluster running when the program panics is helpful during development, as it makes debugging the cluster easier — but I can make that optional so that, by default, it always cleans up the cluster.

I’ll add it to my to-do list and aim to implement it next week. I’m quite busy this week, so it’ll have to wait.

**Comment by dag-andersen** [comment]
Hi @davidfrickert 

[Version 0.0.25](https://github.com/dag-andersen/argocd-diff-preview/releases/tag/v0.0.25) was just released 🚀 This version should cleanup the cluster on failure. Let me know if you experience any issues :)
